name: Run HTML Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install HTML Validator CLI
        run: |
          npm install -g html-validator-cli

      - name: Validate HTML
        run: |
         html-validator --file index.html
